version: "3.9"

services:
  psql:
    image: postgres
    container_name: psql
    environment:
      - POSTGRES_DB=tg_bot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2608
    volumes:
      - ./data:/docker-entrypoint-initdb.d
  telegram-bot:
    container_name: telegram-bot
    volumes:
      - ./bot:/bot
    env_file: .env
    restart: always
    build:
        context: ./bot
        dockerfile: Dockerfile
    command: sh -c "python main.py"

volumes:
  postgres_data: